disabled_rules: # rule identifiers to exclude from running
 - cyclomatic_complexity
 - shorthand_operator
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods

