name: Source Composition Analysis Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security-sca:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --all-projects --json-file-output=snyk.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
      - uses: contentstack/sca-policy@main