name: Source Composition Analysis Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security-sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      # Set up GitHub Token for authentication with private repos
      - name: Set up GitHub Token
        run: |
         git config --global url."https://x-access-token:${{ secrets.PKG_TOKEN }}@github.com".insteadOf "https://github.com"
         git config --global url."https://x-access-token:${{ secrets.PKG_TOKEN }}@github.com".insteadOf "git@github.com:"
      - name: Resolve Swift package dependencies
        run: swift package resolve 
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --all-projects --fail-on=all
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
