name: Source Composition Analysis Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security-sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      # - name: Set up GitHub Token for Swift Package Manager
      #   run: |
      #     git config --global url."https://x-access-token:${{ secrets.PKG_TOKEN }}@github.com/".insteadOf "https://github.com/"
      
      # # Step 4: Resolve Swift package dependencies
      # - name: Resolve Swift package dependencies
      #   run: swift package resolve
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PKG_TOKEN }} 
      - name: Configure Git credentials
        run: |
          touch ~/.gitconfig
          git config --global url."https://x-access-token:${{ secrets.PKG_TOKEN }}@github.com/".insteadOf "https://github.com/"
    
      - name: Resolve Swift package dependencies
        run: swift package resolve
        env:
          GITHUB_TOKEN: ${{ secrets.PKG_TOKEN }}
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --all-projects --fail-on=all
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PKG_TOKEN }} 
      - name: Cleanup credentials
        if: always()
        run: rm -f ~/.gitconfig
